### ISSUE TITLE
Drag and drop install to eclipse not working

### ISSUE THREAD

**Issue by phillipjwall** [blackducksoftware/hub-eclipse-plugin#2]
Dragging the Install to eclipse opens the Eclipse Marketplace but does not start the install, does not bring up the plugin. Even searching in the Eclipse Marketplace you are not able to find the Black Duck Plugin. Any thoughts? with Eclipse SimRel 2018-09

**Comment by rottebds** [comment]
Unfortunately, @phillipjwall, this integration does not support versions of Eclipse later than Oxygen. As of time of writing, we don't plan to support Photon or later versions.
