### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by kernelGadaffi** [blackducksoftware/hub-eclipse-plugin#22]
Dear all

Can't wait to try out this plugin on our installation of black duck hub. But I got https://10.0.0.102,javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.

Any setting to allow unverified certificates?

**Comment by akamen** [comment]
@kernelGadaffi  no setting sadly for that version of Hub Eclipse, please import the proper certificates into your Java security lib directory!
